apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mern-production-cluster
  region: ap-south-1
  version: "1.30"

managedNodeGroups:
  - name: mern-microservices-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 30
    privateNetworking: true
    iam:
      withAddonPolicies:
        cloudWatch: true
        albIngress: true

